// types.js

export const SAVE_LOGIN_RESPONSE = 'SAVE_LOGIN_RESPONSE';
export const CONTACT_US_RESPONSE = 'CONTACT_US_RESPONSE';
export const SAVE_TESTIMONIAL_RESPONSE = 'SAVE_TESTIMONIAL_RESPONSE';
export const SAVE_SLIDES_RESPONSE = 'SAVE_SLIDES_RESPONSE';

